group: stable
sudo: false
language: ruby
addons:
  postgresql: '9.3'
  apt:
    packages:
      - graphviz
rvm:
  - 2.7.2
script:
  - bundle exec rake spec
  - bundle exec rake cucumber
  - bundle exec rake yard
